export const ComponentIDs = {
  addProjectMenuItem: 'addProjectMenuItem',
  addProjectFormName: 'addProjectFormName',
  addProjectFormPicture: 'addProjectFormPicture',
  addProjectFormHomePage: 'addProjectFormHomePage',
  addProjectFormDescription: 'addProjectFormDescription',
  addProjectFormInterests: 'addProjectFormInterests',
  addProjectFormParticipants: 'addProjectFormParticipants',
  addProjectFormSubmit: 'addProjectFormSubmit',
  addSpotMenuItem: 'add-spot-menu-item',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterFormInterests: 'filterFormInterests',
  filterFormSubmit: 'filterFormSubmit',
  filterMenuItem: 'filterMenuItem',
  homeFormFirstName: 'homeFormFirstName',
  homeFormLastName: 'homeFormLastName',
  homeFormBio: 'homeFormBio',
  homeFormSubmit: 'homeFormSubmit',
  homeMenuItem: 'homeMenuItem',
  interestsMenuItem: 'interestsMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  mapMenuItem: 'map-menu-item',
  profilesMenuItem: 'profilesMenuItem',
  projectsMenuItem: 'projectsMenuItem',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  addSpotPage: 'addSpotPage', // Added this line
  filterPage: 'filterPage',
  homePage: 'homePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
};
